# loxmatter - connects Matter devices to a Loxone Miniserver.
# Copyright (C) 2026 Lucien Kerl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Reads the signal/command key that `loxmatter` itself assigned, from the
fields where it already sits in the project file (design section 3.3) -
`Check` for inputs, `CmdOn`/`CmdOff` for outputs. This is the same key
that `model.store._assign_key` assigns and that `export.documents`/
`export.outputs` write into exactly these fields."""

from __future__ import annotations

from collections.abc import Mapping

_CMD_PREFIX = "/cmd/"


def key_from_check(check: str) -> str | None:
    """The part before the first colon in a check pattern, e.g.
    ``"d3_1_onoff:\\v"`` -> ``"d3_1_onoff"``. `None` without a colon - then
    the pattern does not come from `loxmatter` (see `render_virtual_in_udp`,
    which always writes `Check` as ``f"{key}:{suffix}"``)."""
    if ":" not in check:
        return None
    return check.split(":", 1)[0]


def key_from_cmd_on(cmd_on: str) -> str | None:
    """The key from a command path generated by `loxmatter`, e.g.
    ``"/cmd/d3_1_onoff/1"`` -> ``"d3_1_onoff"``. `None` for any path that
    does not start with ``/cmd/`` - that is the marker by which its own
    output commands are distinguished from all others (``/toggle``,
    ``/write?db=...``) (see `export.outputs._command_path`)."""
    if not cmd_on.startswith(_CMD_PREFIX):
        return None
    rest = cmd_on[len(_CMD_PREFIX) :]
    key = rest.split("/", 1)[0]
    return key or None


def key_from_output_cmd(attrs: Mapping[str, str]) -> str | None:
    """The key of an existing `VirtualOutCmd` - from `CmdOn` AND `CmdOff`
    together, not from `CmdOn` alone.

    The reason is the combined on/off output from `export.outputs.
    to_outputs`: on the rising edge it sends the same path as the
    individual `on` command (`/cmd/d1_1_on/1`), and differs from it only
    by its `CmdOff`. Read from `CmdOn` alone, both would get the same key
    - in the index one would then overwrite the other, and the combined
    command would be nowhere to be found under its real key
    (``"d1_1_on + d1_1_off"``, as `to_outputs` assigns it). That was
    exactly the user report of "a new onoff field after export and
    re-import": another duplicate on every run, because the comparison
    did not recognise its own output.

    A `CmdOff` that does not come from `loxmatter` (or is missing/empty)
    does not change the key - then the on command counts on its own."""
    on = key_from_cmd_on(attrs.get("CmdOn", ""))
    if on is None:
        return None
    off = key_from_cmd_on(attrs.get("CmdOff", ""))
    return f"{on} + {off}" if off is not None else on
